service: myfitnesspal

provider:
  name: aws
  runtime: python3.7
  region: eu-central-1
  timeout: 15
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "*"

functions:
  fetch:
    handler: fetch.lambda_handler 
    events:
      - schedule: cron(0 5 * * ? *)
#      - schedule: rate(10 minutes)
#    Define function environment variables here
    environment:
      user: placeholder
      password: placeholder

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
